name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile Java source files
      run: javac HelloWorld.java

    - name: Run tests
      run: java HelloWorld

